#! /usr/bin/env ansible-playbook
# Configure haproxy role
# Replace 'haproxy' with your own inventory group
---
- name: haproxy | load balancer and reverse proxy
  hosts: haproxy
  roles:
  - role: haproxy
    tags:
    - haproxy
