#! /usr/bin/env ansible-playbook
# Uninstall role
# Run prior to removing host from inventory groups, so hostvars are accessible
---
- name: haproxy | uninstall
  hosts: all
  tasks:
  - include_role:
      name: haproxy
      tasks_from: uninstall.yml
